config/routes.rb
LearnChinese::Application.routes.draw do
  get "admin/index"
  get "admin/lessons"
  get "admin/words"
  get "admin/concepts"
  get "admin/word_new"
  get "lessons/index"
  get "trainer/index"
  get "trainer/number"
  get "trainer/direction"
  get "trainer/color"
  get "welcome/index"
  get "welcome/about"
  get "welcome/login"

  root to: 'welcome#index'

  resources :words
  resources :concepts
  resources :lessons do
    resources :concepts
  end

  

end

app/models/concept.rb
class Concept < ActiveRecord::Base

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
	has_many :concept

	def new
	end
end

app/models/type.rb
class Type < ActiveRecord::Base
end

app/models/word.rb
class Word < ActiveRecord::Base
	has_many :types

	private
		def post_params
			params.require(:word).permit(:translation, :pinyn, :character, :types)
		end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @title = "Admin"
  end

  def lessons
    @title = "Admin-Lessons"
    @lessons = Lesson.all
    @lesson = Lesson.new
  end

  def words
    @title = "Admin-Words"
    @words = Word.all
  end

  def concepts
    @title = "Admin-Concepts"
    @concept = Concept.new
  	@concepts = Concept.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/concepts_controller.rb
class ConceptsController < ApplicationController

	def create
		@concept = Concept.new(params[:concept].permit(:sentence, :translation, :tags))

		@concept.save
		redirect_to :admin_concepts
	end

	def edit
		@concept = Concept.find(params[:id])

	end

	def destroy
		@concept = Concept.find(params[:id])
		@concept.destroy
		
		redirect_to :admin_concepts
	end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController

	def index
		@title = "Lessons overview"
		@lessons = Lesson.all
	end

	def show
		@lesson = Lesson.find(params[:id])
		@title = @lesson.title
	end

	def test
		@lesson = Lesson.new
		@lesson.title = "A Test Lesson"
		@lesson.description = "Some description"
		
	end
end

app/controllers/trainer_controller.rb
class TrainerController < ApplicationController
  
  def index
  	@title = "Trainers"
  end

  def number
  	@title = "Number Trainer"
  end

  def direction
  	@title = "Directions Trainer"
  end

  def color
  	@title = "Color Trainer"
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
  
  def about
  	@title = "About"
  end

end

app/controllers/words_controller.rb
class WordsController < ApplicationController
	def create
		@word = Word.new(params[:word].permit(:pinyn, :translation, :character, :types))

		@word.save
		redirect_to :admin_words
	end

	def edit

	end

	def destroy
		@word = Word.find(params[:id])
		@word.destroy
		
		redirect_to :admin_words
	end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/concept_helper.rb
module ConceptHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/trainer_helper.rb
module TrainerHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/admin/_subnav.html.erb
<ul class="nav nav-pills">
  <li><%= link_to "Home", admin_index_path %></li>
  <li><%= link_to "Words", admin_words_path %></li>
  <li><%= link_to "Concepts", admin_concepts_path %></li>
  <li><%= link_to "Lessons", admin_lessons_path %></li>
</ul>
<br>

app/views/admin/concepts.html.erb
	<p>
		<div class="btn btn-primary" id="add_concept_button">add Concept</div>
	</p>	
	<table class="table table-hover">
		<tr>
			<th>ID</th>
			<th>Sentence</th>
			<th>Translation</th>
			<th>Tags</th>
			<th>&nbsp;</th>
			<!-- <th>Types</th> -->
		</tr>
	<% @concepts.each do |concept| %>
		<tr>
			<td><%= concept.id %></td>
			<td><%= concept.sentence %></td>
			<td><%= concept.translation %></td>
			<td width="140"><%= concept.tags %></td>
			<td><%= link_to raw("<span class='glyphicon glyphicon-pencil'/>"), edit_concept_path(concept) %> &nbsp; &nbsp; &nbsp;
			<%= link_to raw("<span class='glyphicon glyphicon-remove'/>"), concept_path(concept), method: :delete, data: {confirm: "You really want to delete this concept?"} %></td>
		</tr>
	<% end %>
</table>

<!--- Finished Modal Dialog -->
	<div id="addConceptDialog" tabindex="-1" role="dialog" aria-labelledby="addConceptDialog" aria-hidden="true" class="modal fade">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" data-dismiss="modal" aria-hidden="true" class="close">×</button>
	        <center> 
	          <h4 class="modal-title">Add new Concept</h4>
	        </center>
	      </div>
	      <%= form_for(@concept) do |f| %>
	      <div class="modal-body">
					<%= f.label :sentence, "Concept" %>
					<%= f.text_field :sentence, :placeholder => "Concept sentence", :class => "form-control" %>
					<%= f.label :translation, "Translated" %>
					<%= f.text_field :translation, :placeholder => "Translated senctence", :class => "form-control" %>
					<%= f.label :tags, "Tags" %>
					<%= f.text_field :tags, :placeholder => "Tags", :class => "form-control" %>
	      </div>
	      <div class="modal-footer">
	        <button type="button" data-dismiss="modal" id="closeButton" class="btn btn-default">Close</button>
		  	<%= f.submit "Save", :disable_with => 'Saveing...', :class => "btn btn-success" %>
	        <!-- <button type="button" id="againButton" class="btn btn-primary"></button> -->
	      </div>
			<% end %> 
	    </div>
	  </div>
	</div>
</div>
<script type="text/javascript" src="/assets/admin.js"></script>

app/views/admin/lessons.html.erb
	<p>
		<div class="btn btn-primary" id="add_concept_button">+Lesson</div>
	</p>	
	<table class="table table-hover">
		<tr>
			<th>ID</th>
			<th>Title</th>
			<th>Description</th>
			<th>Concepts</th>
			<th>&nbsp;</th>
			<!-- <th>Types</th> -->
		</tr>
	<% @lessons.each do |lesson| %>
		<tr>
			<td><%= lessons.id %></td>
			<td><%= lessons.title %></td>
			<td><%= lessons.description %></td>
			<% lessons.concept.each do || %>

			<% end %>
			<td><%= link_to raw("<span class='glyphicon glyphicon-pencil'/>"), edit_concept_path(concept) %> &nbsp; &nbsp; &nbsp;
			<%= link_to raw("<span class='glyphicon glyphicon-remove'/>"), concept_path(concept), method: :delete, data: {confirm: "You really want to delete this concept?"} %></td>
		</tr>
	<% end %>
</table>

<!--- Finished Modal Dialog -->
	<div id="addConceptDialog" tabindex="-1" role="dialog" aria-labelledby="addConceptDialog" aria-hidden="true" class="modal fade">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" data-dismiss="modal" aria-hidden="true" class="close">×</button>
	        <center> 
	          <h4 class="modal-title">Add new Concept</h4>
	        </center>
	      </div>
	      <%= form_for(@lesson) do |f| %>
	      <div class="modal-body">
					<%= f.label :title, "Title" %>
					<%= f.text_field :title, :placeholder => "Lesson title", :class => "form-control" %>
					<%= f.label :description, "Description" %>
					<%= f.text_area :description, :placeholder => "Short description of the lesson", :class => "form-control" %>
					<p>
						<div class="row">
							<div class="col-md-5">
								<%= f.label :concept, "Selected Concepts", :class => "control-label" %><br>
								<%= f.select( :concept,  {}, {}, {:class => "form-control", :multiple => true}  )%>
							</div>
							<div class="col-xs-2" >
								<br><br>
								<span class="glyphicon glyphicon-chevron-left" id="button_add_selected_concept"></span>
								<br><br>
								<span class="glyphicon glyphicon-chevron-right" id="button_remove_selected_concept"></span>
							</div>
							<div class="col-md-5">
								<%= f.label :allConcepts, "Available Concepts", :class => "control-label" %>
								<%= select("allConcepts", "concept_id", Concept.all.collect {|c| [ c.sentence, c.id ] }, {}, {:class => "form-control", :multiple => true }) %>
								<!-- <select name="availableConcepts" id="availableConcepts" class="form-control" multiple size="5"> -->
								<!-- <label for="availableConcepts" class="control-label">Selected Concepts</label> -->
									
								</select>
							</div>
						</div>
					</p>
	      </div>
	      <div class="modal-footer">
	        <button type="button" data-dismiss="modal" id="closeButton" class="btn btn-default">Close</button>
		  	<%= f.submit "Save", :disable_with => 'Saveing...', :class => "btn btn-success" %>
	        <!-- <button type="button" id="againButton" class="btn btn-primary"></button> -->
	      </div>
			<% end %> 
	    </div>
	  </div>
	</div>
</div>
<script type="text/javascript" src="/assets/admin.js"></script>

app/views/admin/words.html.erb
	<p>
		<div class="btn btn-primary" id="add_word_button">New Word</div>
	</p>
	<p>
		<div class="row" id="add_word_row" >
			<%= form_for(Word.new) do |f| %>
				<div class="col-lg-3">
					<%= f.label :translation, "Word" %>
					<%= f.text_field :translation, :placeholder => "Word in english", :class => "form-control" %>
				</div>
				<div class="col-lg-3">
					<%= f.label :pinyn, "Pinyn" %>
					<%= f.text_field :pinyn, :placeholder => "Pinyn", :class => "form-control" %>
				</div>
				<div class="col-lg-2">
					<%= f.label :character, "Character" %>
					<%= f.text_field :character, :placeholder => "Chinese character", :class => "form-control" %>
				</div>	
<!-- 				<div class="col-lg-3">
					<%= f.label :types, "Type" %>
					<%= f.text_field :types, :placeholder => "Type", :class => "form-control" %>
				</div> -->
				<div class="col-lg-1">
		  			<%= f.submit "Save", :disable_with => 'Saveing...', :class => "btn btn-success" %>
		  		</div>
			<% end %>
		</div>
		</p>
	<table class="table table-hover">
		<tr>
			<th>ID</th>
			<th>Word</th>
			<th>Pinyn</th>
			<th>Character</th>
			<th>&nbsp;</th>
			<!-- <th>Types</th> -->
		</tr>
	<% @words.each do |word| %>
		<tr>
			<td><%= word.id %></td>
			<td><%= word.translation %></td>
			<td><%= word.pinyn %></td>
			<td width="140"><%= word.character %></td>
			<td><%= link_to raw("<span class='glyphicon glyphicon-pencil'/>"), edit_word_path(word) %> &nbsp; &nbsp; &nbsp;
			<%= link_to raw("<span class='glyphicon glyphicon-remove'/>"), word_path(word), method: :delete, data: {confirm: "You really want to delete this word?"} %></td>
			<!-- <td><%= word.types %></td>  -->
		</tr>
	<% end %>
	</table>
</div>

<script type="text/javascript" src="/assets/admin.js"></script>

app/views/application/_navbar.html.erb
  <div class="container">
      <div class="masthead">
        <div class="page-header">
          <%= link_to raw("<h1>Learn Chinese <small>学中文</small></h1>"), root_path %>
        </div>
        <ul class="nav nav-justified">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Lessons", :lessons %></li>
          <li><%= link_to "Trainers", trainer_index_path %></li>
          <li><%= link_to "Admin", admin_index_path %></li>
          <li><%= link_to "About", welcome_about_path %></li>
          <li><%= link_to "Sign in", welcome_login_path %></li>
        </ul>
      </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LearnChinese</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "navbar" %>
<div class="container" style="padding: 15px">
	<div class="container container-bg">
		<h2><%= @title %></h2>
		<%= render 'subnav' %>
		 <%= yield %>
	</div>
</div>

</body>
</html>

app/views/lessons/index.html.erb
  <div class="row">
  <%= @lessons.each do |lesson|%>
        <div class="col-lg-4">
          <h2><%= lesson.title %></h2>
          <p><%= lesson.description %></p>
          <p><%= link_to "Details", lessons_show_path, :class => "btn btn-primary"%></p>
        </div>
  <% end %>
</div>

app/views/trainer/color.html.erb
	<div class="progress" id="progress">
	</div>
	<div class="well well-lg">

		<div class="row">
			<div class="col-md-12" id="description">
				<h4>Description</h4>
			</div>
		</div>
		<br>
		<div class="row">
			<div class="col-md-6"  align="center">
				<div class="row" id="question">
					
				</div>
			</div>
			<div id="user_input_field" class="col-md-6 center-block">
				<input id="user_input_text" type="text" placeholder="The color on the left in chinese" class="form-control" style="display: none;"/>
				<div id="color_fields" class="row" style="display: none;">
					<div class="col-xs-2"><div class="img-rounded color-field" id="0" style="background-color: #000000;"></div></div>
					<div class="col-xs-2"><div class="img-rounded color-field" id="1" style="background-color: #FFFFFF;"></div></div>
					<div class="col-xs-2"><div class="img-rounded color-field" id="2" style="background-color: #FF0000;"></div></div>
					<div class="col-xs-2"><div class="img-rounded color-field" id="3" style="background-color: #008000;"></div></div>
					<div class="col-xs-2"><div class="img-rounded color-field" id="4" style="background-color: #0000FF;"></div></div>
					<br>
					<div class="col-xs-2"><div class="img-rounded color-field" id="5" style="background-color: #FFFF00;"></div></div>
					<div class="col-xs-2"><div class="img-rounded color-field" id="6" style="background-color: #800080;"></div></div>
					<div class="col-xs-2"><div class="img-rounded color-field" id="7" style="background-color: #FFC0CB;"></div></div>
					<div class="col-xs-2"><div class="img-rounded color-field" id="8" style="background-color: #808080;"></div></div>
					<div class="col-xs-2"><div class="img-rounded color-field" id="9" style="background-color: #8B4513;"></div></div>
					<div class="col-xs-2"><div class="img-rounded color-field" id="10" style="background-color: #FFA500;"></div></div>
				</div>
			</div>
		</div>
		<br>
		<div class="row" align="right">
			<div class="col-md-12">
				<button id="checkButton" type="submit" class="btn btn-primary">Check</button>
			</div>
		</div>
	</div>

	<!--- Finished Modal Dialog -->
	<div id="finishedDialog" tabindex="-1" role="dialog" aria-labelledby="finishedDialogLabel" aria-hidden="true" class="modal fade">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" data-dismiss="modal" aria-hidden="true" class="close">×</button>
	        <center> 
	          <h4 class="modal-title">Finished!</h4>
	        </center>
	      </div>
	      <div class="modal-body">
	        <center> 
	          <div id="dialog_message"></div>
	        </center>
	      </div>
	      <div class="modal-footer">
	        <button type="button" data-dismiss="modal" id="closeButton" class="btn btn-default">Close</button>
	        <button type="button" id="againButton" class="btn btn-primary">Play again</button>
	      </div>
	    </div>
	  </div>
	</div>
<script type="text/javascript" src="/assets/trainer_color.js"></script>

app/views/trainer/index.html.erb
<div class="row">
  <div class="col-6 col-sm-6 col-lg-4">
    <%= image_tag "numbers.jpg", :class => "img-rounded size-medium" %>
    <h2>Number Trainer</h2>
    <p><%= link_to "Start exercising", trainer_number_path, :class => "btn btn-default" %></p>
  </div><!--/span-->
  <div class="col-6 col-sm-6 col-lg-4">
    <%= image_tag "colors.jpg", :class => "img-rounded size-medium" %>
    <h2>Color Trainer</h2>
    <p><%= link_to "Start exercising", trainer_color_path, :class => "btn btn-default" %></p>
  </div><!--/span-->
  <div class="col-6 col-sm-6 col-lg-4">
    <%= image_tag "directions.jpg", :class => "img-rounded size-medium" %>
    <h2>Directions Trainer</h2>
    <p><%= link_to "Start exercising", trainer_direction_path, :class => "btn btn-default" %></p>
  </div><!--/span-->
</div><!--/row-->

app/views/trainer/number.html.erb
	<div class="progress" id="progress">
	</div>
	<div class="well well-lg">

		<div class="row">
			<div class="col-md-12">
				<h4> Write down the pinyins for the given number (e.g. 24 = 'er shi si')</h4>
			</div>
		</div>
		<br>
		<div class="row">
			<div class="col-md-6"  align="center">
				<div id="number_field">
					<h3>42</h3>
				</div>
			</div>
			<div class="col-md-6">
				<input id="userInput" type="text" placeholder="The number on the left in chinese" class="form-control"/>
			</div>
		</div>
		<br>
		<div class="row" align="right">
			<div class="col-md-12">
				<button id="checkButton" type="submit" class="btn btn-primary">Check</button>
			</div>
		</div>
	</div>

	<!--- Finished Modal Dialog -->
	<div id="finishedDialog" tabindex="-1" role="dialog" aria-labelledby="finishedDialogLabel" aria-hidden="true" class="modal fade">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" data-dismiss="modal" aria-hidden="true" class="close">×</button>
	        <center> 
	          <h4 class="modal-title">Finished!</h4>
	        </center>
	      </div>
	      <div class="modal-body">
	        <center> 
	          <div id="dialog_message"></div>
	        </center>
	      </div>
	      <div class="modal-footer">
	        <button type="button" data-dismiss="modal" id="closeButton" class="btn btn-default">Close</button>
	        <button type="button" id="againButton" class="btn btn-primary">Play again</button>
	      </div>
	    </div>
	  </div>
	</div>
<script type="text/javascript" src="/assets/trainer_number.js"></script>

app/views/welcome/index.html.erb
    <div class="container">

	     <!-- Main component for a primary marketing message or call to action -->
	    <div class="jumbotron">
		  <h2>Learn Chinese<small>学中文</small></h2>
			<p>
				My little webapp to learn Chinese
			</p>
	       <p>
	       		<%= button_to "Get Started", lessons_index_path, :method => "get", :class => "btn btn-default btn-primary"%>
	       </p>
	    </div>

    </div> <!-- /container -->

app/views/welcome/login.html.erb
    <div class="col-xs-3 col-centered">
      <form class="form-signin">
        <h2 class="form-signin-heading">Please sign in</h2>
        <input type="text" class="form-control" placeholder="Email address" autofocus>
        <input type="password" class="form-control" placeholder="Password">
        <label class="checkbox">
          <input type="checkbox" value="remember-me"> Remember me
        </label>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      </form>
    </div>